# pyproject.toml
[build-system]
requires = ["setuptools>=61.0", "wheel", "ruamel.yaml", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp_registry_servers_utils"
description = "MCP Servers"
authors = [{name = "Vinod Kumar KP", email = "vinodkumar.kp.1985@gmail.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
keywords = ["mcp", "mcp_registry_servers"]
dynamic = ["scripts", "version"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "oai-mcp-server-core",
    "mcp==2.3.0",
    "fastmcp==4.0.11"
]

[tool.uv.sources]
 oai-mcp-server-core = { git = "https://github.com/VinodKumarKP/ptr_oai_adk.git", branch = "main", subdirectory = "packages/mcp-core" }


[project.urls]
Homepage = "https://github.com//{repo_name}"
Repository = "https://github.com//{repo_name}.gi"
Issues = "https://github.com/{repo_name}/issues"


[tool.setuptools.packages.find]
where = ["."]
include = ["mcp_registry_servers*"]
exclude = [".venv", "build", "mcp_registry_servers.egg_info", "tests"]

[tool.setuptools.package-data]
"mcp_registry_servers" = ["**/*"]

# Configuration for setuptools_scm (git-based versioning)
[tool.setuptools_scm]
write_to = "mcp_registry_servers/_version.py"
version_scheme = "post-release"
local_scheme = "no-local-version"