# pyproject.toml
[build-system]
requires = ["setuptools>=61.0", "wheel", "ruamel.yaml", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp_registry_servers_{{category}}"
description = "MCP Servers"
authors = [{name = "Vinod Kumar KP", email = "{Email address of the author}"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
keywords = ["mcp", "mcp_registry_servers"]
dynamic = ["scripts", "version"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "oai-mcp-server-core@git+https://github.com/Capgemini-Innersource/ptr_mcp_server_core@main"
]


[project.urls]
Homepage = "https://github.com/Capgemini-Innersource/{repo_name}"
Repository = "https://github.com/Capgemini-Innersource/{repo_name}.gi"
Issues = "https://github.com/Capgemini-Innersource/{repo_name}/issues"


[tool.setuptools.packages.find]
where = ["."]
include = ["mcp_registry_servers*"]
exclude = [".venv", "build", "mcp_registry_servers.egg_info", "tests"]

[tool.setuptools.package-data]
"mcp_registry_servers" = ["**/*"]

# Configuration for setuptools_scm (git-based versioning)
[tool.setuptools_scm]
write_to = "mcp_registry_servers/_version.py"
version_scheme = "post-release"
local_scheme = "no-local-version"